### ISSUE TITLE
No opportunity to request account closure

### ISSUE THREAD

**Issue by abea** [lefnire/jobpig#10]
I think it's an important ethical and technological responsibility for web apps to have a clear path to delete account information. I saw no indication of this in the profile section or anywhere else obvious.

**Comment by lefnire** [comment]
Good call, will add tomorrow. Hope you're well Alex, long time no talk!

**Comment by lefnire** [comment]
Fixed in fc2396c ([screen](https://i.gyazo.com/e6815de9a9e1017b23a5b7eb2243d9c4.png)). Glad to fulfill my ethical responsibility; hope it saved starving children.

**Comment by lefnire** [comment]
(hard refresh; CDN-cached, I'll add a ticket for invalidation hashing)

**Comment by abea** [comment]
Thanks, man. Sorry if I sounded harsh! I was giving it a spin and generally thought it was cool, but also am not going to be looking for a job and am obsessive about stray accounts. Going through my 1Password Watchtower has made me really appreciate this feature.

**Comment by lefnire** [comment]
Ah, makes sense! Thanks for test-driving :)
